<img src="images/usm.jpg" width="480" height="240" align="left"/>

# MAT281 - Laboratorio N°02

## Objetivos de la clase

* Reforzar los conceptos básicos de numpy.

## Contenidos

* [Problema 01](#p1)
* [Problema 02](#p2)
* [Problema 03](#p3)

In [5]:
import numpy as np
import time
import sys

<a id='p1'></a>

## Problema 01

Una **media móvil simple** (SMA) es el promedio de los últimos $k$ datos anteriores, es decir, sea $a_1$,$a_2$,...,$a_n$ un arreglo $n$-dimensional, entonces la SMA se define por:

$$sma(k) =\dfrac{1}{k}(a_{n}+a_{n-1}+...+a_{n-(k-1)}) = \dfrac{1}{k}\sum_{i=0}^{k-1}a_{n-i}  $$ 


Por otro lado podemos definir el SMA con una venta móvil de $n$ si el resultado nos retorna la el promedio ponderado avanzando de la siguiente forma:

* $a = [1,2,3,4,5]$, la SMA con una ventana de $n=2$ sería:


    * sma(2): [mean(1,2),mean(2,3),mean(3,4)] = [1.5, 2.5, 3.5, 4.5]
    * sma(3): [mean(1,2,3),mean(2,3,4),mean(3,4,5)] = [2.,3.,4.]


Implemente una función llamada `sma` cuyo input sea un arreglo unidimensional $a$ y un entero $n$, y cuyo ouput retorne el valor de la media móvil simple sobre el arreglo de la siguiente forma:

* **Ejemplo**: *sma([5,3,8,10,2,1,5,1,0,2], 2)* = $[4. , 5.5, 9. , 6. , 1.5, 3. , 3. , 0.5, 1. ]$

En este caso, se esta calculando el SMA para un arreglo con una ventana de $n=2$.

**Hint**: utilice la función `numpy.cumsum`

In [2]:
np.cumsum([5,3,8,10,2,1,5,1,0,2],dtype=float)

array([ 5.,  8., 16., 26., 28., 29., 34., 35., 35., 37.])

In [3]:
def sma(a,n):
    l = np.cumsum(a)
    lista = []
    for i in range(n-1,len(l)):
        if i == n-1:
            lista.append(l[n-1]/n)
        else:
            lista.append((l[i]-l[i-n])/n)
    return lista
            
            

In [4]:
sma([5,3,8,10,2,1,5,1,0,2], 2)

[4.0, 5.5, 9.0, 6.0, 1.5, 3.0, 3.0, 0.5, 1.0]

<a id='p2'></a>

## Problema 02

La función **strides($a,n,p$)**, corresponde a transformar un arreglo unidimensional $a$ en una matriz de $n$ columnas, en el cual las filas se van construyendo desfasando la posición del arreglo en $p$ pasos hacia adelante.

* Para el arreglo unidimensional $a$ = [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], la función strides($a,4,2$), corresponde a crear una matriz de $4$ columnas, cuyos desfaces hacia adelante se hacen de dos en dos. 

El resultado tendría que ser algo así:$$\begin{pmatrix}
 1& 2 &3 &4 \\ 
 3&  4&5&6 \\ 
 5& 6 &7 &8 \\ 
 7& 8 &9 &10 \\ 
\end{pmatrix}$$


Implemente una función llamada `strides(a,4,2)` cuyo input sea un arreglo unidimensional y retorne la matriz de $4$ columnas, cuyos desfaces hacia adelante se hacen de dos en dos. 

* **Ejemplo**: *strides($a$,4,2)* =$\begin{pmatrix}
 1& 2 &3 &4 \\ 
 3&  4&5&6 \\ 
 5& 6 &7 &8 \\ 
 7& 8 &9 &10 \\ 
\end{pmatrix}$


In [23]:
#Example for dummies
a=[1,2,3,4,5,6,7,8,9]
n=3
p=1
numero = int((len(a)-n+p)/p)
m= np.zeros((numero,n))
m[1][1]=2
print(m)

[[0. 0. 0.]
 [0. 2. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [24]:
def strides(a,n,p):
    filas = int((len(a)-n+p)/p)
    matriz = np.zeros((filas,n))
    for i in range(0,filas):
        matriz[i:]=a[i*p:n+i*p]
    return matriz
        

In [26]:
#ejemplo
strides([1,2,3,4,5,6,7,8,9],3,1)

array([[1., 2., 3.],
       [2., 3., 4.],
       [3., 4., 5.],
       [4., 5., 6.],
       [5., 6., 7.],
       [6., 7., 8.],
       [7., 8., 9.]])

<a id='p3'></a>

## Problema 03


Un **cuadrado mágico** es una matriz de tamaño $n \times n$ de números enteros positivos tal que 
la suma de los números por columnas, filas y diagonales principales sea la misma. Usualmente, los números empleados para rellenar las casillas son consecutivos, de 1 a $n^2$, siendo $n$ el número de columnas y filas del cuadrado mágico.

Si los números son consecutivos de 1 a $n^2$, la suma de los números por columnas, filas y diagonales principales 
es igual a : $$M_{n} = \dfrac{n(n^2+1)}{2}$$
Por ejemplo, 

* $A= \begin{pmatrix}
 4& 9 &2 \\ 
 3&  5&7 \\ 
 8& 1 &6 
\end{pmatrix}$,
es un cuadrado mágico.

* $B= \begin{pmatrix}
 4& 2 &9 \\ 
 3&  5&7 \\ 
 8& 1 &6 
\end{pmatrix}$, no es un cuadrado mágico.

Implemente una función llamada `es_cudrado_magico` cuyo input sea una matriz cuadrada de tamaño $n$ con números consecutivos de $1$ a $n^2$ y cuyo ouput retorne *True* si es un cuadrado mágico o 'False', en caso contrario

* **Ejemplo**: *es_cudrado_magico($A$)* = True, *es_cudrado_magico($B$)* = False

**Hint**: Cree una función que valide la mariz es cuadrada y  que sus números son consecutivos del 1 a $n^2$.

In [96]:
def validar(A):
    tupla = np.shape(A)
    n=tupla[0]
    conjunto = set()
    if tupla[0] == tupla[1]:
        for i in range(0,n):
            for k in range(n):
                if A[i][k] <= n*n and A[i][k]>0:
                    conjunto.add(A[i][k])
                else:
                    return False
        if len(conjunto) == n*n:
            return True
        else:
            return False
        
    else:
        return False
    
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[1,2,3],[4,5,6]])
C = np.array([[1,1,1],[4,5,6],[7,8,24]])
print(validar(A))
print(validar(B))
print(validar(C))

True
False
False


In [117]:
def es_cuadrado_magico(A):
    tupla=np.shape(A)
    n=tupla[0]
    m=(n*(n**2 + 1))/2
    transpuesta = A.T
    flag = True
    if validar(A):
        for i in range(0,n):
            if m == sum(A[i]) and sum(A[i]) == sum(transpuesta[i]) and np.trace(A) == sum(A[i]):
                None
            else:
                flag = False
    else:
        return False
    return flag

In [119]:
A = np.array([[4,2,2],[3,1,7],[8,1,6]])
print(es_cuadrado_magico(A))

False
